### ISSUE TITLE
Validatie geeft

### ISSUE THREAD

**Issue by Theo-denBlanken** [N1ght02/jquery#1]
Je hebt feedback gekregen van **Theo-denBlanken**
URL: https://github.com/N1ght02/jquery/blob/master/index.html

Feedback: 5 errors[](http://www.studiozoetekauw.nl/codereview-in-het-onderwijs/ '#cr:{"sha":"f1b3f41d618b8f9b626d1a124288f569291ce1e8","path":"index.html","reviewer":"Theo-denBlanken"}')

**Comment by N1ght02** [comment]
Ik heb de code gevalideerd zijn er geen errors meer
