### ISSUE TITLE
jQuery plugin ontbreekt:

### ISSUE THREAD

**Issue by Theo-denBlanken** [N1ght02/jquery#2]
Je hebt feedback gekregen van **Theo-denBlanken**
URL: https://github.com/N1ght02/jquery/blob/master/index.html

Feedback: Voeg naar eigen inzicht een jQuery plugin aan deze pagina toe. Als je het beter vindt, dan mag je dat ook op een aparte pagina doen en vanuit jouw training daar een link naar leggen. 
Zie bijvoorbeeld ter inspiratie:

https://kenwheeler.github.io/slick/

https://speckyboy.com/free-jquery-plugins/

https://lokeshdhakar.com/projects/lightbox2/;

http://bla.hosts.ma-cloud.nl/20-mooie-jquery-plugins/

https://www.vandelaydesign.com/30-best-free-jquery-plugins/?utm_source=Vandelay&utm_campaign=4b50ff3c3c-RSS_EMAIL_CAMPAIGN&utm_medium=email&utm_term=0_64c66699ed-4b50ff3c3c-295182717[](http://www.studiozoetekauw.nl/codereview-in-het-onderwijs/ '#cr:{"sha":"f1b3f41d618b8f9b626d1a124288f569291ce1e8","path":"index.html","reviewer":"Theo-denBlanken"}')

**Comment by N1ght02** [comment]
Ik heb de vide plugin gebruikt en die stelt een video in als achtergrond 
Bron: https://plugins.jquery.com/vide/ en https://github.com/VodkaBears/Vide
