### ISSUE TITLE
Afbeelding gestretched

### ISSUE THREAD

**Issue by Theo-denBlanken** [N1ght02/jquery#3]
Je hebt feedback gekregen van **Theo-denBlanken**
URL: https://github.com/N1ght02/jquery/blob/master/index.html

Feedback: je kunt: 
óf breedte óf hoogte vrijlaten

óf de afbeeldingen in PhotoShop vooraf de juiste afmetingen/verhoudingen geven

óf de afbeelding bijsnijden:
https://dev.to/teroauralinna/crop-and-resize-images-with-css-444h

https://alligator.io/css/cropping-images-object-fit/

https://www.calliaweb.co.uk/hard-soft-crop/[](http://www.studiozoetekauw.nl/codereview-in-het-onderwijs/ '#cr:{"sha":"f1b3f41d618b8f9b626d1a124288f569291ce1e8","path":"index.html","reviewer":"Theo-denBlanken"}')

**Comment by N1ght02** [comment]
Ik heb dit gedaan en de afbeelding zijn nu niet meer gestretched
